files:
  # English source files
  - source: /locales/en/*.json
    translation: /locales/%two_letters_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        id: id  # Indonesian language mapping

  # Specific rules for common.json
  - source: /locales/en/common.json
    translation: /locales/%two_letters_code%/common.json

  # Specific rules for security.json
  - source: /locales/en/security.json
    translation: /locales/%two_letters_code%/security.json
