name: Update i18n submodule

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: Yurasubs/yuramedia
          token: ${{ secrets.PAT_TOKEN }}
          submodules: true
          ssh-strict: true
          ssh-user: git
          persist-credentials: true
          clean: true
          sparse-checkout-cone-mode: true
          fetch-depth: 1
          fetch-tags: false
          show-progress: true
          lfs: false
          set-safe-directory: true

      - name: Pull & update the i18n submodule
        run: |
          git submodule update --init --recursive src/locales
          git submodule update --remote src/locales

      - name: Commit changes for i18n submodule
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions - update submodules"
          git add src/locales
          git commit -m "chore(i18n): sync git submodule" || echo "No changes to commit"
          git push
